version: '3.6'

services:

  mariadb:
    image: mariadb:10.2.12
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./conf/mariadb-conf/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
      - ./conf/mariadb-conf/init.sql:/home/init.sql
      - mariadb-data-volumes:/var/lib/mysql
    ports:
      - "3307:3306"

  nginx:
    image: nginx:1.13.12-alpine
    ports:
      - "8088:80"
    volumes:
      - ./conf/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-apps-volumes:/home/frappe/bench/apps

  redis-cache:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf/redis_cache.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-queue:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf/redis_queue.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./conf/redis-conf/redis_socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  frappe:
    image: parsemaker/erpnext:production
    environment:
      - benchNewSiteName=prdsite1.local
    ports:
      - "8000:8000"   #webserver_port
      - "9000:9000"   #socketio_port
      - "6787:6787"   #file_watcher_port
    volumes:
      - ./conf/frappe-docker-conf/init.sh:/home/frappe/init.sh
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-apps-volumes:/home/frappe/bench/apps
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true

volumes:
  frappe-sites-volumes:
  frappe-apps-volumes:
  frappe-logs-volumes:
  mariadb-data-volumes:

